var graduateData = [
  {
    "id": "1",
    "school": "강릉여고",
    "name": "김민지",
    "uniRegion": "비수도권",
    "uniRegionCity": "부산",
    "uniName": null,
    "occu": "공무원",
    "residence": "비수도권",
    "residenceCity": "강릉",
    "hometown": "O",
    "interview": null,
    "clickOff": null,
    "noGraphic": null
  },
  {
    "id": "2",
    "school": "강릉여고",
    "name": "김보라",
    "uniRegion": "비수도권",
    "uniRegionCity": "춘천",
    "uniName": null,
    "occu": "공무원",
    "residence": "비수도권",
    "residenceCity": "춘천",
    "hometown": null,
    "interview": null,
    "clickOff": null,
    "noGraphic": null
  },
  {
    "id": "3",
    "school": "강릉여고",
    "name": "김서희",
    "uniRegion": "비수도권",
    "uniRegionCity": "춘천",
    "uniName": null,
    "occu": "직장인",
    "residence": "비수도권",
    "residenceCity": "강릉",
    "hometown": "O",
    "interview": "O",
    "clickOff": null,
    "noGraphic": null
  },
  {
    "id": "4",
    "school": "강릉여고",
    "name": "김은비",
    "uniRegion": "수도권",
    "uniRegionCity": "부천",
    "uniName": null,
    "occu": "IT기획자",
    "residence": "수도권",
    "residenceCity": "서울",
    "hometown": null,
    "interview": "O",
    "clickOff": null,
    "noGraphic": null
  },
  {
    "id": "5",
    "school": "강릉여고",
    "name": "김현주",
    "uniRegion": "수도권",
    "uniRegionCity": "수원",
    "uniName": null,
    "occu": "영화마케터",
    "residence": "수도권",
    "residenceCity": "서울",
    "hometown": null,
    "interview": "O",
    "clickOff": null,
    "noGraphic": null
  },
  {
    "id": "6",
    "school": "강릉여고",
    "name": "김혜림",
    "uniRegion": "비수도권",
    "uniRegionCity": "강원도",
    "uniName": null,
    "occu": "그래픽디자이너",
    "residence": "수도권",
    "residenceCity": "서울",
    "hometown": null,
    "interview": "O",
    "clickOff": null,
    "noGraphic": null
  },
  {
    "id": "7",
    "school": "강릉여고",
    "name": "박수현",
    "uniRegion": "비수도권",
    "uniRegionCity": "원주",
    "uniName": null,
    "occu": "미상",
    "residence": "미상",
    "residenceCity": "미상",
    "hometown": null,
    "interview": null,
    "clickOff": "O",
    "noGraphic": "O"
  },
  {
    "id": "8",
    "school": "강릉여고",
    "name": "박예슬",
    "uniRegion": "비수도권",
    "uniRegionCity": "춘천",
    "uniName": null,
    "occu": "간호사",
    "residence": "수도권",
    "residenceCity": "서울",
    "hometown": null,
    "interview": "O",
    "clickOff": null,
    "noGraphic": null
  },
  {
    "id": "9",
    "school": "강릉여고",
    "name": "박지현",
    "uniRegion": "수도권",
    "uniRegionCity": "서울",
    "uniName": null,
    "occu": "공무원",
    "residence": "수도권",
    "residenceCity": "서울",
    "hometown": null,
    "interview": null,
    "clickOff": null,
    "noGraphic": null
  },
  {
    "id": "10",
    "school": "강릉여고",
    "name": "서예진",
    "uniRegion": "수도권",
    "uniRegionCity": "서울",
    "uniName": null,
    "occu": "기자",
    "residence": "수도권",
    "residenceCity": "서울",
    "hometown": null,
    "interview": "O",
    "clickOff": null,
    "noGraphic": null
  },
  {
    "id": "11",
    "school": "강릉여고",
    "name": "서진영",
    "uniRegion": "비수도권",
    "uniRegionCity": "춘천",
    "uniName": null,
    "occu": "공무원",
    "residence": "비수도권",
    "residenceCity": "강릉",
    "hometown": "O",
    "interview": null,
    "clickOff": null,
    "noGraphic": null
  },
  {
    "id": "12",
    "school": "강릉여고",
    "name": "송은지",
    "uniRegion": "수도권",
    "uniRegionCity": "서울",
    "uniName": null,
    "occu": "문화예술계종사",
    "residence": "비수도권",
    "residenceCity": "강릉",
    "hometown": "O",
    "interview": "O",
    "clickOff": null,
    "noGraphic": null
  },
  {
    "id": "13",
    "school": "강릉여고",
    "name": "장예원",
    "uniRegion": "비수도권",
    "uniRegionCity": "부산",
    "uniName": null,
    "occu": "미술작가",
    "residence": "비수도권",
    "residenceCity": "부산",
    "hometown": null,
    "interview": null,
    "clickOff": null,
    "noGraphic": null
  },
  {
    "id": "14",
    "school": "강릉여고",
    "name": "임성희",
    "uniRegion": "비수도권",
    "uniRegionCity": "강릉",
    "uniName": null,
    "occu": "간호사",
    "residence": "수도권",
    "residenceCity": "서울",
    "hometown": null,
    "interview": null,
    "clickOff": null,
    "noGraphic": null
  },
  {
    "id": "15",
    "school": "강릉여고",
    "name": "이효진",
    "uniRegion": "비수도권",
    "uniRegionCity": null,
    "uniName": null,
    "occu": "직장인",
    "residence": "수도권",
    "residenceCity": "수원",
    "hometown": null,
    "interview": null,
    "clickOff": null,
    "noGraphic": "O"
  },
  {
    "id": "16",
    "school": "강릉여고",
    "name": "이혜린",
    "uniRegion": "비수도권",
    "uniRegionCity": "춘천",
    "uniName": null,
    "occu": "학원강사",
    "residence": "비수도권",
    "residenceCity": "강릉",
    "hometown": "O",
    "interview": null,
    "clickOff": null,
    "noGraphic": null
  },
  {
    "id": "17",
    "school": "강릉여고",
    "name": "이현임",
    "uniRegion": "대학X",
    "uniRegionCity": null,
    "uniName": null,
    "occu": "문화예술계종사",
    "residence": "비수도권",
    "residenceCity": "강릉",
    "hometown": "O",
    "interview": "O",
    "clickOff": null,
    "noGraphic": null
  },
  {
    "id": "18",
    "school": "강릉여고",
    "name": "이지연",
    "uniRegion": "수도권",
    "uniRegionCity": "인천",
    "uniName": null,
    "occu": "주부",
    "residence": "비수도권",
    "residenceCity": "세종",
    "hometown": null,
    "interview": "O",
    "clickOff": null,
    "noGraphic": null
  },
  {
    "id": "19",
    "school": "강릉여고",
    "name": "이윤지",
    "uniRegion": "비수도권",
    "uniRegionCity": "춘천",
    "uniName": null,
    "occu": "공기업",
    "residence": "비수도권",
    "residenceCity": "강릉",
    "hometown": null,
    "interview": null,
    "clickOff": null,
    "noGraphic": null
  },
  {
    "id": "20",
    "school": "강릉여고",
    "name": "이슬비",
    "uniRegion": "미상",
    "uniRegionCity": "미상",
    "uniName": null,
    "occu": "미상",
    "residence": "미상",
    "residenceCity": "미상",
    "hometown": null,
    "interview": null,
    "clickOff": "O",
    "noGraphic": "O"
  },
  {
    "id": "21",
    "school": "강릉여고",
    "name": "이수지",
    "uniRegion": "비수도권",
    "uniRegionCity": "창원",
    "uniName": null,
    "occu": "승무원",
    "residence": "비수도권",
    "residenceCity": "대구",
    "hometown": null,
    "interview": null,
    "clickOff": null,
    "noGraphic": null
  },
  {
    "id": "22",
    "school": "강릉여고",
    "name": "이성령",
    "uniRegion": "수도권",
    "uniRegionCity": "서울",
    "uniName": null,
    "occu": "공무원",
    "residence": "비수도권",
    "residenceCity": "속초",
    "hometown": null,
    "interview": "O",
    "clickOff": null,
    "noGraphic": null
  },
  {
    "id": "23",
    "school": "강릉여고",
    "name": "심수민",
    "uniRegion": "미상",
    "uniRegionCity": "미상",
    "uniName": null,
    "occu": "미상",
    "residence": "미상",
    "residenceCity": "미상",
    "hometown": null,
    "interview": null,
    "clickOff": "O",
    "noGraphic": "O"
  },
  {
    "id": "24",
    "school": "강릉여고",
    "name": "신상미",
    "uniRegion": "수도권",
    "uniRegionCity": "인천",
    "uniName": null,
    "occu": "교사",
    "residence": "수도권",
    "residenceCity": "경기",
    "hometown": null,
    "interview": null,
    "clickOff": null,
    "noGraphic": null
  },
  {
    "id": "25",
    "school": "강릉여고",
    "name": "전여빈",
    "uniRegion": "수도권",
    "uniRegionCity": "서울",
    "uniName": null,
    "occu": "배우",
    "residence": "수도권",
    "residenceCity": "서울",
    "hometown": null,
    "interview": null,
    "clickOff": null,
    "noGraphic": null
  },
  {
    "id": "26",
    "school": "강릉여고",
    "name": "최소희",
    "uniRegion": "비수도권",
    "uniRegionCity": "춘천",
    "uniName": null,
    "occu": "직장인",
    "residence": "수도권",
    "residenceCity": "서울",
    "hometown": null,
    "interview": "O",
    "clickOff": null,
    "noGraphic": null
  },
  {
    "id": "27",
    "school": "강릉여고",
    "name": "장희정",
    "uniRegion": "수도권",
    "uniRegionCity": "용인·서울",
    "uniName": null,
    "occu": "직장인",
    "residence": "수도권",
    "residenceCity": "서울",
    "hometown": null,
    "interview": "O",
    "clickOff": null,
    "noGraphic": null
  },
  {
    "id": "28",
    "school": "강릉여고",
    "name": "정원희",
    "uniRegion": "비수도권",
    "uniRegionCity": "강릉",
    "uniName": null,
    "occu": "공무원",
    "residence": "비수도권",
    "residenceCity": "청주",
    "hometown": null,
    "interview": null,
    "clickOff": null,
    "noGraphic": null
  },
  {
    "id": "29",
    "school": "강릉여고",
    "name": "조아람",
    "uniRegion": "비수도권",
    "uniRegionCity": "고성·원주·경기양주",
    "uniName": null,
    "occu": "미상",
    "residence": "미상",
    "residenceCity": "미상",
    "hometown": null,
    "interview": null,
    "clickOff": "O",
    "noGraphic": "O"
  },
  {
    "id": "30",
    "school": "강릉여고",
    "name": "주지현",
    "uniRegion": "비수도권",
    "uniRegionCity": "강릉",
    "uniName": null,
    "occu": "안경사",
    "residence": "비수도권",
    "residenceCity": "강릉",
    "hometown": "O",
    "interview": null,
    "clickOff": null,
    "noGraphic": null
  },
  {
    "id": "31",
    "school": "강릉여고",
    "name": "주효정",
    "uniRegion": "수도권",
    "uniRegionCity": "서울",
    "uniName": null,
    "occu": "공공기관",
    "residence": "수도권",
    "residenceCity": "서울",
    "hometown": null,
    "interview": null,
    "clickOff": null,
    "noGraphic": null
  },
  {
    "id": "32",
    "school": "강릉여고",
    "name": "최고운",
    "uniRegion": "수도권",
    "uniRegionCity": "서울",
    "uniName": null,
    "occu": "주부",
    "residence": "수도권",
    "residenceCity": "서울",
    "hometown": null,
    "interview": "O",
    "clickOff": null,
    "noGraphic": null
  },
  {
    "id": "33",
    "school": "강릉여고",
    "name": "최민지",
    "uniRegion": "수도권",
    "uniRegionCity": "서울",
    "uniName": null,
    "occu": "기자",
    "residence": "수도권",
    "residenceCity": "서울",
    "hometown": null,
    "interview": null,
    "clickOff": null,
    "noGraphic": null
  },
  {
    "id": "34",
    "school": "강릉여고",
    "name": "최현지",
    "uniRegion": "미상",
    "uniRegionCity": "미상",
    "uniName": null,
    "occu": "미상",
    "residence": "미상",
    "residenceCity": "미상",
    "hometown": null,
    "interview": null,
    "clickOff": "O",
    "noGraphic": "O"
  },
  {
    "id": "35",
    "school": "강릉여고",
    "name": "탄예신",
    "uniRegion": "수도권",
    "uniRegionCity": "서울",
    "uniName": null,
    "occu": "미상",
    "residence": "미상",
    "residenceCity": "미상",
    "hometown": null,
    "interview": null,
    "clickOff": "O",
    "noGraphic": "O"
  },
  {
    "id": "36",
    "school": "강릉여고",
    "name": "허아현",
    "uniRegion": "수도권",
    "uniRegionCity": "서울",
    "uniName": null,
    "occu": "직장인",
    "residence": "수도권",
    "residenceCity": "분당",
    "hometown": null,
    "interview": "O",
    "clickOff": null,
    "noGraphic": null
  },
  {
    "id": "37",
    "school": "고창여고",
    "name": "강선주",
    "uniRegion": "비수도권",
    "uniRegionCity": "전남",
    "uniName": "전남대",
    "occu": "공무원",
    "residence": "비수도권",
    "residenceCity": "고창",
    "hometown": "O",
    "interview": "O",
    "clickOff": null,
    "noGraphic": null
  },
  {
    "id": "38",
    "school": "고창여고",
    "name": "강은",
    "uniRegion": "수도권",
    "uniRegionCity": "서울",
    "uniName": "고려대",
    "occu": "기자",
    "residence": "수도권",
    "residenceCity": "서울",
    "hometown": null,
    "interview": null,
    "clickOff": null,
    "noGraphic": null
  },
  {
    "id": "39",
    "school": "고창여고",
    "name": "강지희",
    "uniRegion": "비수도권",
    "uniRegionCity": "전북",
    "uniName": "전북대",
    "occu": "공시생",
    "residence": "비수도권",
    "residenceCity": "비수도권",
    "hometown": null,
    "interview": null,
    "clickOff": null,
    "noGraphic": "O"
  },
  {
    "id": "40",
    "school": "고창여고",
    "name": "공근영",
    "uniRegion": "비수도권",
    "uniRegionCity": null,
    "uniName": null,
    "occu": "간호사",
    "residence": "수도권",
    "residenceCity": "부천",
    "hometown": null,
    "interview": "O",
    "clickOff": null,
    "noGraphic": "O"
  },
  {
    "id": "41",
    "school": "고창여고",
    "name": "길단비",
    "uniRegion": "수도권",
    "uniRegionCity": "용인",
    "uniName": "용인대",
    "occu": "미상",
    "residence": "비수도권",
    "residenceCity": "고창",
    "hometown": "O",
    "interview": null,
    "clickOff": null,
    "noGraphic": null
  },
  {
    "id": "42",
    "school": "고창여고",
    "name": "김나경",
    "uniRegion": "미상",
    "uniRegionCity": "미상",
    "uniName": null,
    "occu": "미상",
    "residence": "미상",
    "residenceCity": "미상",
    "hometown": null,
    "interview": null,
    "clickOff": "O",
    "noGraphic": "O"
  },
  {
    "id": "43",
    "school": "고창여고",
    "name": "김수진",
    "uniRegion": "미상",
    "uniRegionCity": "미상",
    "uniName": null,
    "occu": "미상",
    "residence": "미상",
    "residenceCity": "미상",
    "hometown": null,
    "interview": null,
    "clickOff": "O",
    "noGraphic": "O"
  },
  {
    "id": "44",
    "school": "고창여고",
    "name": "김은주",
    "uniRegion": "비수도권",
    "uniRegionCity": "전남",
    "uniName": "조선대",
    "occu": "방송 디자이너",
    "residence": "비수도권",
    "residenceCity": "전주",
    "hometown": null,
    "interview": null,
    "clickOff": null,
    "noGraphic": null
  },
  {
    "id": "45",
    "school": "고창여고",
    "name": "김혜란",
    "uniRegion": "비수도권",
    "uniRegionCity": "전남",
    "uniName": "조선대",
    "occu": "미상",
    "residence": "미상",
    "residenceCity": "미상",
    "hometown": null,
    "interview": null,
    "clickOff": "O",
    "noGraphic": "O"
  },
  {
    "id": "46",
    "school": "고창여고",
    "name": "김혜인",
    "uniRegion": "비수도권",
    "uniRegionCity": null,
    "uniName": null,
    "occu": "은행",
    "residence": "비수도권",
    "residenceCity": "고창",
    "hometown": "O",
    "interview": null,
    "clickOff": null,
    "noGraphic": "O"
  },
  {
    "id": "47",
    "school": "고창여고",
    "name": "김희진",
    "uniRegion": "수도권",
    "uniRegionCity": "서울",
    "uniName": "연세대",
    "occu": "은행",
    "residence": "수도권",
    "residenceCity": "서울",
    "hometown": null,
    "interview": null,
    "clickOff": null,
    "noGraphic": null
  },
  {
    "id": "48",
    "school": "고창여고",
    "name": "박좌연",
    "uniRegion": "비수도권",
    "uniRegionCity": "전남",
    "uniName": "전남대",
    "occu": "공공기관",
    "residence": "비수도권",
    "residenceCity": "전주",
    "hometown": null,
    "interview": null,
    "clickOff": null,
    "noGraphic": null
  },
  {
    "id": "49",
    "school": "고창여고",
    "name": "봉아현",
    "uniRegion": "비수도권",
    "uniRegionCity": null,
    "uniName": null,
    "occu": "유치원교사",
    "residence": "비수도권",
    "residenceCity": "광주",
    "hometown": null,
    "interview": null,
    "clickOff": null,
    "noGraphic": "O"
  },
  {
    "id": "50",
    "school": "고창여고",
    "name": "서승현",
    "uniRegion": "수도권",
    "uniRegionCity": null,
    "uniName": null,
    "occu": "직장인",
    "residence": "수도권",
    "residenceCity": "서울",
    "hometown": null,
    "interview": null,
    "clickOff": null,
    "noGraphic": null
  },
  {
    "id": "51",
    "school": "고창여고",
    "name": "서지은",
    "uniRegion": "비수도권",
    "uniRegionCity": "전남",
    "uniName": "광주대",
    "occu": "승무원",
    "residence": "수도권",
    "residenceCity": "서울",
    "hometown": null,
    "interview": null,
    "clickOff": null,
    "noGraphic": null
  },
  {
    "id": "52",
    "school": "고창여고",
    "name": "손지희",
    "uniRegion": "비수도권",
    "uniRegionCity": null,
    "uniName": null,
    "occu": "간호사",
    "residence": "비수도권",
    "residenceCity": "군산",
    "hometown": null,
    "interview": "O",
    "clickOff": null,
    "noGraphic": "O"
  },
  {
    "id": "53",
    "school": "고창여고",
    "name": "유효정",
    "uniRegion": "미상",
    "uniRegionCity": "미상",
    "uniName": null,
    "occu": "미상",
    "residence": "미상",
    "residenceCity": "미상",
    "hometown": null,
    "interview": null,
    "clickOff": "O",
    "noGraphic": "O"
  },
  {
    "id": "54",
    "school": "고창여고",
    "name": "이아네스",
    "uniRegion": "비수도권",
    "uniRegionCity": "전북",
    "uniName": "원광대",
    "occu": "미상",
    "residence": "미상",
    "residenceCity": "미상",
    "hometown": null,
    "interview": null,
    "clickOff": "O",
    "noGraphic": "O"
  },
  {
    "id": "55",
    "school": "고창여고",
    "name": "이지수",
    "uniRegion": "비수도권",
    "uniRegionCity": "미상",
    "uniName": null,
    "occu": "미상",
    "residence": "미상",
    "residenceCity": "미상",
    "hometown": null,
    "interview": null,
    "clickOff": "O",
    "noGraphic": "O"
  },
  {
    "id": "56",
    "school": "고창여고",
    "name": "이하현",
    "uniRegion": "수도권",
    "uniRegionCity": null,
    "uniName": null,
    "occu": "미상",
    "residence": "수도권",
    "residenceCity": "서울",
    "hometown": null,
    "interview": null,
    "clickOff": "O",
    "noGraphic": "O"
  },
  {
    "id": "57",
    "school": "고창여고",
    "name": "이현주",
    "uniRegion": "수도권",
    "uniRegionCity": "서울",
    "uniName": "중앙대 평생교육원",
    "occu": "아르바이트",
    "residence": "수도권",
    "residenceCity": "서울",
    "hometown": null,
    "interview": null,
    "clickOff": null,
    "noGraphic": null
  },
  {
    "id": "58",
    "school": "고창여고",
    "name": "이희지",
    "uniRegion": "수도권",
    "uniRegionCity": "인천",
    "uniName": "인하공전",
    "occu": "건축사",
    "residence": "수도권",
    "residenceCity": "서울",
    "hometown": null,
    "interview": "O",
    "clickOff": null,
    "noGraphic": null
  },
  {
    "id": "59",
    "school": "고창여고",
    "name": "정경화",
    "uniRegion": "비수도권",
    "uniRegionCity": "전남",
    "uniName": "전남대",
    "occu": "미상",
    "residence": "미상",
    "residenceCity": "미상",
    "hometown": null,
    "interview": null,
    "clickOff": "O",
    "noGraphic": "O"
  },
  {
    "id": "60",
    "school": "고창여고",
    "name": "정다윤",
    "uniRegion": "비수도권",
    "uniRegionCity": "전남",
    "uniName": "광주대",
    "occu": "유튜버, 모델",
    "residence": "수도권",
    "residenceCity": "서울",
    "hometown": null,
    "interview": null,
    "clickOff": null,
    "noGraphic": null
  },
  {
    "id": "61",
    "school": "고창여고",
    "name": "정소원",
    "uniRegion": "미상",
    "uniRegionCity": null,
    "uniName": null,
    "occu": "시험준비",
    "residence": "수도권",
    "residenceCity": "서울",
    "hometown": null,
    "interview": null,
    "clickOff": null,
    "noGraphic": "O"
  },
  {
    "id": "62",
    "school": "고창여고",
    "name": "조민정",
    "uniRegion": "비수도권",
    "uniRegionCity": "전남",
    "uniName": "조선대",
    "occu": "간호사",
    "residence": "수도권",
    "residenceCity": "서울",
    "hometown": null,
    "interview": "O",
    "clickOff": null,
    "noGraphic": null
  },
  {
    "id": "63",
    "school": "고창여고",
    "name": "조수진",
    "uniRegion": "수도권",
    "uniRegionCity": null,
    "uniName": null,
    "occu": "간호조무사",
    "residence": "수도권",
    "residenceCity": "서울",
    "hometown": null,
    "interview": null,
    "clickOff": null,
    "noGraphic": null
  },
  {
    "id": "64",
    "school": "고창여고",
    "name": "최하미",
    "uniRegion": "비수도권",
    "uniRegionCity": null,
    "uniName": null,
    "occu": "공무원",
    "residence": "비수도권",
    "residenceCity": "전주",
    "hometown": null,
    "interview": null,
    "clickOff": null,
    "noGraphic": "O"
  },
  {
    "id": "65",
    "school": "고창여고",
    "name": "한승윤",
    "uniRegion": "비수도권",
    "uniRegionCity": "전북",
    "uniName": "군산대",
    "occu": "구직중",
    "residence": "수도권",
    "residenceCity": "서울",
    "hometown": null,
    "interview": null,
    "clickOff": null,
    "noGraphic": null
  }
];